# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        self.confirm_button = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.confirm_button.setGeometry(QtCore.QRect(450, 440, 171, 32))
        self.confirm_button.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.confirm_button.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.confirm_button.setObjectName("confirm_button")
        self.label_select_steps = QtWidgets.QLabel(parent=Dialog)
        self.label_select_steps.setGeometry(QtCore.QRect(20, 10, 251, 16))
        self.label_select_steps.setObjectName("label_select_steps")
        self.progressBar = QtWidgets.QProgressBar(parent=Dialog)
        self.progressBar.setGeometry(QtCore.QRect(30, 410, 581, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.processing_txt_box = QtWidgets.QTextBrowser(parent=Dialog)
        self.processing_txt_box.setGeometry(QtCore.QRect(20, 170, 591, 231))
        self.processing_txt_box.setObjectName("processing_txt_box")
        self.label_AI_confidence = QtWidgets.QLabel(parent=Dialog)
        self.label_AI_confidence.setGeometry(QtCore.QRect(20, 80, 131, 16))
        self.label_AI_confidence.setObjectName("label_AI_confidence")
        self.radioButton_AI_normal = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_AI_normal.setGeometry(QtCore.QRect(160, 80, 99, 20))
        self.radioButton_AI_normal.setObjectName("radioButton_AI_normal")
        self.radioButton_AI_high = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_AI_high.setGeometry(QtCore.QRect(230, 80, 51, 20))
        self.radioButton_AI_high.setAcceptDrops(True)
        self.radioButton_AI_high.setAutoFillBackground(True)
        self.radioButton_AI_high.setChecked(False)
        self.radioButton_AI_high.setObjectName("radioButton_AI_high")
        self.radioButton_bird_small = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_bird_small.setGeometry(QtCore.QRect(160, 110, 51, 20))
        self.radioButton_bird_small.setObjectName("radioButton_bird_small")
        self.radioButton_bird_normal = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_bird_normal.setGeometry(QtCore.QRect(230, 110, 51, 20))
        self.radioButton_bird_normal.setAcceptDrops(True)
        self.radioButton_bird_normal.setAutoFillBackground(True)
        self.radioButton_bird_normal.setChecked(False)
        self.radioButton_bird_normal.setObjectName("radioButton_bird_normal")
        self.label_bird_ratio = QtWidgets.QLabel(parent=Dialog)
        self.label_bird_ratio.setGeometry(QtCore.QRect(20, 110, 111, 16))
        self.label_bird_ratio.setObjectName("label_bird_ratio")
        self.radioButton_bird_large = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_bird_large.setGeometry(QtCore.QRect(300, 110, 51, 20))
        self.radioButton_bird_large.setAcceptDrops(True)
        self.radioButton_bird_large.setAutoFillBackground(True)
        self.radioButton_bird_large.setChecked(False)
        self.radioButton_bird_large.setObjectName("radioButton_bird_large")
        self.label_bird_sharpness = QtWidgets.QLabel(parent=Dialog)
        self.label_bird_sharpness.setGeometry(QtCore.QRect(20, 140, 111, 16))
        self.label_bird_sharpness.setObjectName("label_bird_sharpness")
        self.radioButton_sharpness_clear = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_sharpness_clear.setGeometry(QtCore.QRect(230, 140, 51, 20))
        self.radioButton_sharpness_clear.setAcceptDrops(True)
        self.radioButton_sharpness_clear.setAutoFillBackground(True)
        self.radioButton_sharpness_clear.setChecked(False)
        self.radioButton_sharpness_clear.setObjectName("radioButton_sharpness_clear")
        self.radioButton_sharpness_normal = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_sharpness_normal.setGeometry(QtCore.QRect(160, 140, 51, 20))
        self.radioButton_sharpness_normal.setObjectName("radioButton_sharpness_normal")
        self.radioButton_sharpness_extra_clear = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_sharpness_extra_clear.setGeometry(QtCore.QRect(300, 140, 51, 20))
        self.radioButton_sharpness_extra_clear.setAcceptDrops(True)
        self.radioButton_sharpness_extra_clear.setAutoFillBackground(True)
        self.radioButton_sharpness_extra_clear.setChecked(True)
        self.radioButton_sharpness_extra_clear.setObjectName("radioButton_sharpness_extra_clear")
        self.label_contact_email = QtWidgets.QLabel(parent=Dialog)
        self.label_contact_email.setGeometry(QtCore.QRect(30, 440, 311, 16))
        self.label_contact_email.setObjectName("label_contact_email")
        self.layoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 40, 591, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.select_dir_layout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.select_dir_layout.setContentsMargins(0, 0, 0, 0)
        self.select_dir_layout.setObjectName("select_dir_layout")
        self.display_dir_box = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.display_dir_box.setText("")
        self.display_dir_box.setObjectName("display_dir_box")
        self.select_dir_layout.addWidget(self.display_dir_box)
        self.browse_dir_button = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.browse_dir_button.setObjectName("browse_dir_button")
        self.select_dir_layout.addWidget(self.browse_dir_button)

        self.retranslateUi(Dialog)
        self.confirm_button.accepted.connect(Dialog.accept) # type: ignore
        self.confirm_button.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.display_dir_box, self.processing_txt_box)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "SuperPicky V0.01"))
        self.label_select_steps.setText(_translate("Dialog", "选择你的RAW 格式鸟图目录："))
        self.processing_txt_box.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">开始处理中....</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:700;\">处理完成xxx 张照片，其中 SuperPicky 选择值得后期处理的照片有 XXXX张，有鸟但是不符合最优选择的有 xxx张，没有有的照片有多少张，总共耗时多少秒！</span></p></body></html>"))
        self.label_AI_confidence.setText(_translate("Dialog", "选择AI 处理置信度："))
        self.radioButton_AI_normal.setText(_translate("Dialog", "正常"))
        self.radioButton_AI_high.setText(_translate("Dialog", "高"))
        self.radioButton_bird_small.setText(_translate("Dialog", "小"))
        self.radioButton_bird_normal.setText(_translate("Dialog", "正常"))
        self.label_bird_ratio.setText(_translate("Dialog", "选择鸟画面占比："))
        self.radioButton_bird_large.setText(_translate("Dialog", "大"))
        self.label_bird_sharpness.setText(_translate("Dialog", "选择鸟清晰度："))
        self.radioButton_sharpness_clear.setText(_translate("Dialog", "清晰"))
        self.radioButton_sharpness_normal.setText(_translate("Dialog", "常规"))
        self.radioButton_sharpness_extra_clear.setText(_translate("Dialog", "数毛"))
        self.label_contact_email.setText(_translate("Dialog", "技术支持：james@jamesphotography.com.au"))
        self.browse_dir_button.setText(_translate("Dialog", "选择目录"))

