# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QButtonGroup


class Ui_Dialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        self.confirm_button = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.confirm_button.setGeometry(QtCore.QRect(450, 440, 171, 32))
        self.confirm_button.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.confirm_button.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.confirm_button.setObjectName("confirm_button")
        self.label_select_steps = QtWidgets.QLabel(parent=Dialog)
        self.label_select_steps.setGeometry(QtCore.QRect(20, 10, 251, 16))
        self.label_select_steps.setObjectName("label_select_steps")
        self.progressBar = QtWidgets.QProgressBar(parent=Dialog)
        self.progressBar.setGeometry(QtCore.QRect(30, 410, 581, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.processing_txt_box = QtWidgets.QTextBrowser(parent=Dialog)
        self.processing_txt_box.setGeometry(QtCore.QRect(20, 170, 591, 231))
        self.processing_txt_box.setObjectName("processing_txt_box")
        self.label_AI_confidence = QtWidgets.QLabel(parent=Dialog)
        self.label_AI_confidence.setGeometry(QtCore.QRect(20, 80, 131, 16))
        self.label_AI_confidence.setObjectName("label_AI_confidence")
        self.radioButton_AI_normal = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_AI_normal.setGeometry(QtCore.QRect(160, 80, 99, 20))
        self.radioButton_AI_normal.setObjectName("radioButton_AI_normal")
        self.radioButton_AI_normal.setAcceptDrops(True)
        self.radioButton_AI_normal.setAutoFillBackground(True)
        self.radioButton_AI_normal.setChecked(True)
        self.radioButton_AI_high = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_AI_high.setGeometry(QtCore.QRect(230, 80, 51, 20))
        self.radioButton_AI_high.setAcceptDrops(True)
        self.radioButton_AI_high.setAutoFillBackground(True)
        self.radioButton_AI_high.setChecked(False)
        self.radioButton_AI_high.setObjectName("radioButton_AI_high")
        self.radioButton_bird_small = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_bird_small.setGeometry(QtCore.QRect(160, 110, 51, 20))
        self.radioButton_bird_small.setObjectName("radioButton_bird_small")
        self.radioButton_bird_small.setAcceptDrops(True)
        self.radioButton_bird_small.setAutoFillBackground(True)
        self.radioButton_bird_small.setChecked(False)
        self.radioButton_bird_normal = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_bird_normal.setGeometry(QtCore.QRect(230, 110, 51, 20))
        self.radioButton_bird_normal.setAcceptDrops(True)
        self.radioButton_bird_normal.setAutoFillBackground(True)
        self.radioButton_bird_normal.setObjectName("radioButton_bird_normal")
        self.label_bird_ratio = QtWidgets.QLabel(parent=Dialog)
        self.label_bird_ratio.setGeometry(QtCore.QRect(20, 110, 111, 16))
        self.label_bird_ratio.setObjectName("label_bird_ratio")
        self.radioButton_bird_large = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_bird_large.setGeometry(QtCore.QRect(300, 110, 51, 20))
        self.radioButton_bird_large.setAcceptDrops(True)
        self.radioButton_bird_large.setAutoFillBackground(True)
        self.radioButton_bird_large.setChecked(False)
        self.radioButton_bird_large.setObjectName("radioButton_bird_large")
        self.label_bird_sharpness = QtWidgets.QLabel(parent=Dialog)
        self.label_bird_sharpness.setGeometry(QtCore.QRect(20, 140, 111, 16))
        self.label_bird_sharpness.setObjectName("label_bird_sharpness")
        self.radioButton_sharpness_clear = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_sharpness_clear.setGeometry(QtCore.QRect(230, 140, 51, 20))
        self.radioButton_sharpness_clear.setAcceptDrops(True)
        self.radioButton_sharpness_clear.setAutoFillBackground(True)
        self.radioButton_sharpness_clear.setChecked(False)
        self.radioButton_sharpness_clear.setObjectName("radioButton_sharpness_clear")
        self.radioButton_sharpness_normal = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_sharpness_normal.setGeometry(QtCore.QRect(160, 140, 51, 20))
        self.radioButton_sharpness_normal.setObjectName("radioButton_sharpness_normal")
        self.radioButton_sharpness_extra_clear = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_sharpness_extra_clear.setGeometry(QtCore.QRect(300, 140, 51, 20))
        self.radioButton_sharpness_extra_clear.setAcceptDrops(True)
        self.radioButton_sharpness_extra_clear.setAutoFillBackground(True)
        self.radioButton_sharpness_extra_clear.setChecked(False)
        self.radioButton_sharpness_extra_clear.setObjectName("radioButton_sharpness_extra_clear")
        self.label_contact_email = QtWidgets.QLabel(parent=Dialog)
        self.label_contact_email.setGeometry(QtCore.QRect(30, 440, 311, 16))
        self.label_contact_email.setObjectName("label_contact_email")
        self.layoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 40, 591, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.select_dir_layout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.select_dir_layout.setContentsMargins(0, 0, 0, 0)
        self.select_dir_layout.setObjectName("select_dir_layout")
        self.display_dir_box = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.display_dir_box.setText("")
        self.display_dir_box.setObjectName("display_dir_box")
        self.select_dir_layout.addWidget(self.display_dir_box)
        self.browse_dir_button = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.browse_dir_button.setObjectName("browse_dir_button")
        self.select_dir_layout.addWidget(self.browse_dir_button)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.display_dir_box, self.processing_txt_box)

        Dialog.closeEvent = self.customCloseEvent
        # Create button groups
        self.groupAIConfidence = QButtonGroup(Dialog)
        self.groupBirdRatio = QButtonGroup(Dialog)
        self.groupBirdSharpness = QButtonGroup(Dialog)

        # Add radio buttons to their respective groups
        self.groupAIConfidence.addButton(self.radioButton_AI_normal)
        self.groupAIConfidence.addButton(self.radioButton_AI_high)

        self.groupBirdRatio.addButton(self.radioButton_bird_small)
        self.groupBirdRatio.addButton(self.radioButton_bird_normal)
        self.groupBirdRatio.addButton(self.radioButton_bird_large)

        self.groupBirdSharpness.addButton(self.radioButton_sharpness_normal)
        self.groupBirdSharpness.addButton(self.radioButton_sharpness_clear)
        self.groupBirdSharpness.addButton(self.radioButton_sharpness_extra_clear)

        """ JAMES 可编辑 （设置 default）"""
        self.radioButton_AI_normal.setChecked(True)
        self.radioButton_bird_normal.setChecked(True)
        self.radioButton_sharpness_clear.setChecked(True)


    def retranslateUi(self, Dialog):
        eagle_ascii = """
                   __
                 /  (
                /    \\\\
               /      \\\\
              /  0  0  \\\\
        ((\\__/  (_()()()()()
        (      \\\\       /
         \\\\ \\\\    )=====(  /
          \\\\ \\\\  /        \\\\ 
        """

        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "SuperPicky V0.01"))
        self.label_select_steps.setText(_translate("Dialog", "选择你的RAW 格式鸟图目录："))
        self.processing_txt_box.setText(_translate("Dialog", "SuperPicky 程序待命中......\n打鸟一时爽，选片帮你忙......\n"+eagle_ascii))
        self.label_AI_confidence.setText(_translate("Dialog", "选择AI 处理置信度："))
        self.radioButton_AI_normal.setText(_translate("Dialog", "正常"))
        self.radioButton_AI_high.setText(_translate("Dialog", "高"))
        self.radioButton_bird_small.setText(_translate("Dialog", "小"))
        self.radioButton_bird_normal.setText(_translate("Dialog", "正常"))
        self.label_bird_ratio.setText(_translate("Dialog", "选择鸟画面占比："))
        self.radioButton_bird_large.setText(_translate("Dialog", "大"))
        self.label_bird_sharpness.setText(_translate("Dialog", "选择鸟清晰度："))
        self.radioButton_sharpness_clear.setText(_translate("Dialog", "普通"))
        self.radioButton_sharpness_normal.setText(_translate("Dialog", "清晰"))
        self.radioButton_sharpness_extra_clear.setText(_translate("Dialog", "数毛"))
        self.label_contact_email.setText(_translate("Dialog", "技术支持：james@jamesphotography.com.au"))
        self.browse_dir_button.setText(_translate("Dialog", "选择目录"))

    def customCloseEvent(self, event):
        # Force close the application
        sys.stdout = sys.__stdout__
        QtCore.QCoreApplication.instance().quit()

    """ JAMES 可编辑"""
    def getCurrentSelections(self):
        # For AI Confidence
        global ai_confidence, bird_ratio, sharpness
        if self.radioButton_AI_normal.isChecked():          # default
            ai_confidence = 0.8
        elif self.radioButton_AI_high.isChecked():
            ai_confidence = 0.9

        # For Bird Ratio
        if self.radioButton_bird_small.isChecked():
            bird_ratio = 0.03
        elif self.radioButton_bird_normal.isChecked():      # default
            bird_ratio = 0.05
        elif self.radioButton_bird_large.isChecked():
            bird_ratio = 0.08

        # For Sharpness
        if self.radioButton_sharpness_normal.isChecked():
            sharpness = 800
        elif self.radioButton_sharpness_clear.isChecked():  # default
            sharpness = 1000
        elif self.radioButton_sharpness_extra_clear.isChecked():
            sharpness = 2000

        return ai_confidence, bird_ratio, sharpness