# -*- coding: utf-8 -*-
"""
ISO 3166-1 alpha-2 国家/地区代码显示名 / Display names for ISO 3166-1 alpha-2 codes.

内置中英文双语表，覆盖 `geo_distribution.db` 中出现的全部 233 个代码。
刻意不依赖 pycountry/babel：本项目是纯离线软件，为一张静态表引入运行时依赖
并增大打包体积不划算，而 ISO 3166-1 的国家名极少变动。

A built-in bilingual table covering all 233 codes present in
`geo_distribution.db`. Deliberately avoids pycountry/babel: this is an offline
application, and pulling in a runtime dependency plus packaging weight for a
static table is not worth it — ISO 3166-1 names change very rarely.

未收录的代码回退为代码本身，保证 UI 永远有可显示文本。
Unlisted codes fall back to the raw code so the UI always has displayable text.
"""
from __future__ import annotations

from typing import Dict, Tuple

# {代码: (英文名, 中文名)} / {code: (English, Chinese)}
_NAMES: Dict[str, Tuple[str, str]] = {
    "AD": ("Andorra", "安道尔"),
    "AE": ("United Arab Emirates", "阿联酋"),
    "AF": ("Afghanistan", "阿富汗"),
    "AG": ("Antigua and Barbuda", "安提瓜和巴布达"),
    "AI": ("Anguilla", "安圭拉"),
    "AL": ("Albania", "阿尔巴尼亚"),
    "AM": ("Armenia", "亚美尼亚"),
    "AO": ("Angola", "安哥拉"),
    "AQ": ("Antarctica", "南极洲"),
    "AR": ("Argentina", "阿根廷"),
    "AS": ("American Samoa", "美属萨摩亚"),
    "AT": ("Austria", "奥地利"),
    "AU": ("Australia", "澳大利亚"),
    "AW": ("Aruba", "阿鲁巴"),
    "AX": ("Åland Islands", "奥兰群岛"),
    "AZ": ("Azerbaijan", "阿塞拜疆"),
    "BA": ("Bosnia and Herzegovina", "波黑"),
    "BB": ("Barbados", "巴巴多斯"),
    "BD": ("Bangladesh", "孟加拉国"),
    "BE": ("Belgium", "比利时"),
    "BF": ("Burkina Faso", "布基纳法索"),
    "BG": ("Bulgaria", "保加利亚"),
    "BH": ("Bahrain", "巴林"),
    "BI": ("Burundi", "布隆迪"),
    "BJ": ("Benin", "贝宁"),
    "BM": ("Bermuda", "百慕大"),
    "BN": ("Brunei", "文莱"),
    "BO": ("Bolivia", "玻利维亚"),
    "BQ": ("Caribbean Netherlands", "荷属加勒比"),
    "BR": ("Brazil", "巴西"),
    "BS": ("Bahamas", "巴哈马"),
    "BT": ("Bhutan", "不丹"),
    "BW": ("Botswana", "博茨瓦纳"),
    "BY": ("Belarus", "白俄罗斯"),
    "BZ": ("Belize", "伯利兹"),
    "CA": ("Canada", "加拿大"),
    "CC": ("Cocos (Keeling) Islands", "科科斯群岛"),
    "CD": ("DR Congo", "刚果民主共和国"),
    "CF": ("Central African Republic", "中非共和国"),
    "CG": ("Republic of the Congo", "刚果共和国"),
    "CH": ("Switzerland", "瑞士"),
    "CI": ("Côte d'Ivoire", "科特迪瓦"),
    "CK": ("Cook Islands", "库克群岛"),
    "CL": ("Chile", "智利"),
    "CM": ("Cameroon", "喀麦隆"),
    "CN": ("China", "中国"),
    "CO": ("Colombia", "哥伦比亚"),
    "CR": ("Costa Rica", "哥斯达黎加"),
    "CU": ("Cuba", "古巴"),
    "CV": ("Cabo Verde", "佛得角"),
    "CX": ("Christmas Island", "圣诞岛"),
    "CY": ("Cyprus", "塞浦路斯"),
    "CZ": ("Czechia", "捷克"),
    "DE": ("Germany", "德国"),
    "DJ": ("Djibouti", "吉布提"),
    "DK": ("Denmark", "丹麦"),
    "DM": ("Dominica", "多米尼克"),
    "DO": ("Dominican Republic", "多米尼加"),
    "DZ": ("Algeria", "阿尔及利亚"),
    "EC": ("Ecuador", "厄瓜多尔"),
    "EE": ("Estonia", "爱沙尼亚"),
    "EG": ("Egypt", "埃及"),
    "EH": ("Western Sahara", "西撒哈拉"),
    "ER": ("Eritrea", "厄立特里亚"),
    "ES": ("Spain", "西班牙"),
    "ET": ("Ethiopia", "埃塞俄比亚"),
    "FI": ("Finland", "芬兰"),
    "FJ": ("Fiji", "斐济"),
    "FK": ("Falkland Islands", "福克兰群岛"),
    "FM": ("Micronesia", "密克罗尼西亚"),
    "FO": ("Faroe Islands", "法罗群岛"),
    "FR": ("France", "法国"),
    "GA": ("Gabon", "加蓬"),
    "GB": ("United Kingdom", "英国"),
    "GD": ("Grenada", "格林纳达"),
    "GE": ("Georgia", "格鲁吉亚"),
    "GF": ("French Guiana", "法属圭亚那"),
    "GG": ("Guernsey", "根西岛"),
    "GH": ("Ghana", "加纳"),
    "GL": ("Greenland", "格陵兰"),
    "GM": ("Gambia", "冈比亚"),
    "GN": ("Guinea", "几内亚"),
    "GP": ("Guadeloupe", "瓜德罗普"),
    "GQ": ("Equatorial Guinea", "赤道几内亚"),
    "GR": ("Greece", "希腊"),
    "GS": ("South Georgia", "南乔治亚"),
    "GT": ("Guatemala", "危地马拉"),
    "GU": ("Guam", "关岛"),
    "GW": ("Guinea-Bissau", "几内亚比绍"),
    "GY": ("Guyana", "圭亚那"),
    "HK": ("Hong Kong", "香港"),
    "HN": ("Honduras", "洪都拉斯"),
    "HR": ("Croatia", "克罗地亚"),
    "HT": ("Haiti", "海地"),
    "HU": ("Hungary", "匈牙利"),
    "ID": ("Indonesia", "印度尼西亚"),
    "IE": ("Ireland", "爱尔兰"),
    "IL": ("Israel", "以色列"),
    "IM": ("Isle of Man", "马恩岛"),
    "IN": ("India", "印度"),
    "IQ": ("Iraq", "伊拉克"),
    "IR": ("Iran", "伊朗"),
    "IS": ("Iceland", "冰岛"),
    "IT": ("Italy", "意大利"),
    "JM": ("Jamaica", "牙买加"),
    "JO": ("Jordan", "约旦"),
    "JP": ("Japan", "日本"),
    "KE": ("Kenya", "肯尼亚"),
    "KG": ("Kyrgyzstan", "吉尔吉斯斯坦"),
    "KH": ("Cambodia", "柬埔寨"),
    "KI": ("Kiribati", "基里巴斯"),
    "KM": ("Comoros", "科摩罗"),
    "KN": ("Saint Kitts and Nevis", "圣基茨和尼维斯"),
    "KP": ("North Korea", "朝鲜"),
    "KR": ("South Korea", "韩国"),
    "KW": ("Kuwait", "科威特"),
    "KY": ("Cayman Islands", "开曼群岛"),
    "KZ": ("Kazakhstan", "哈萨克斯坦"),
    "LA": ("Laos", "老挝"),
    "LB": ("Lebanon", "黎巴嫩"),
    "LC": ("Saint Lucia", "圣卢西亚"),
    "LK": ("Sri Lanka", "斯里兰卡"),
    "LR": ("Liberia", "利比里亚"),
    "LS": ("Lesotho", "莱索托"),
    "LT": ("Lithuania", "立陶宛"),
    "LV": ("Latvia", "拉脱维亚"),
    "LY": ("Libya", "利比亚"),
    "MA": ("Morocco", "摩洛哥"),
    "MD": ("Moldova", "摩尔多瓦"),
    "ME": ("Montenegro", "黑山"),
    "MG": ("Madagascar", "马达加斯加"),
    "MH": ("Marshall Islands", "马绍尔群岛"),
    "MK": ("North Macedonia", "北马其顿"),
    "ML": ("Mali", "马里"),
    "MM": ("Myanmar", "缅甸"),
    "MN": ("Mongolia", "蒙古"),
    "MP": ("Northern Mariana Islands", "北马里亚纳群岛"),
    "MQ": ("Martinique", "马提尼克"),
    "MR": ("Mauritania", "毛里塔尼亚"),
    "MS": ("Montserrat", "蒙特塞拉特"),
    "MT": ("Malta", "马耳他"),
    "MU": ("Mauritius", "毛里求斯"),
    "MV": ("Maldives", "马尔代夫"),
    "MW": ("Malawi", "马拉维"),
    "MX": ("Mexico", "墨西哥"),
    "MY": ("Malaysia", "马来西亚"),
    "MZ": ("Mozambique", "莫桑比克"),
    "NA": ("Namibia", "纳米比亚"),
    "NC": ("New Caledonia", "新喀里多尼亚"),
    "NE": ("Niger", "尼日尔"),
    "NF": ("Norfolk Island", "诺福克岛"),
    "NG": ("Nigeria", "尼日利亚"),
    "NI": ("Nicaragua", "尼加拉瓜"),
    "NL": ("Netherlands", "荷兰"),
    "NO": ("Norway", "挪威"),
    "NP": ("Nepal", "尼泊尔"),
    "NR": ("Nauru", "瑙鲁"),
    "NU": ("Niue", "纽埃"),
    "NZ": ("New Zealand", "新西兰"),
    "OM": ("Oman", "阿曼"),
    "PA": ("Panama", "巴拿马"),
    "PE": ("Peru", "秘鲁"),
    "PF": ("French Polynesia", "法属波利尼西亚"),
    "PG": ("Papua New Guinea", "巴布亚新几内亚"),
    "PH": ("Philippines", "菲律宾"),
    "PK": ("Pakistan", "巴基斯坦"),
    "PL": ("Poland", "波兰"),
    "PM": ("Saint Pierre and Miquelon", "圣皮埃尔和密克隆"),
    "PN": ("Pitcairn Islands", "皮特凯恩群岛"),
    "PR": ("Puerto Rico", "波多黎各"),
    "PS": ("Palestine", "巴勒斯坦"),
    "PT": ("Portugal", "葡萄牙"),
    "PW": ("Palau", "帕劳"),
    "PY": ("Paraguay", "巴拉圭"),
    "QA": ("Qatar", "卡塔尔"),
    "RE": ("Réunion", "留尼汪"),
    "RO": ("Romania", "罗马尼亚"),
    "RS": ("Serbia", "塞尔维亚"),
    "RU": ("Russia", "俄罗斯"),
    "RW": ("Rwanda", "卢旺达"),
    "SA": ("Saudi Arabia", "沙特阿拉伯"),
    "SB": ("Solomon Islands", "所罗门群岛"),
    "SC": ("Seychelles", "塞舌尔"),
    "SD": ("Sudan", "苏丹"),
    "SE": ("Sweden", "瑞典"),
    "SH": ("Saint Helena", "圣赫勒拿"),
    "SI": ("Slovenia", "斯洛文尼亚"),
    "SJ": ("Svalbard and Jan Mayen", "斯瓦尔巴和扬马延"),
    "SK": ("Slovakia", "斯洛伐克"),
    "SL": ("Sierra Leone", "塞拉利昂"),
    "SN": ("Senegal", "塞内加尔"),
    "SO": ("Somalia", "索马里"),
    "SR": ("Suriname", "苏里南"),
    "SS": ("South Sudan", "南苏丹"),
    "ST": ("São Tomé and Príncipe", "圣多美和普林西比"),
    "SV": ("El Salvador", "萨尔瓦多"),
    "SY": ("Syria", "叙利亚"),
    "SZ": ("Eswatini", "斯威士兰"),
    "TC": ("Turks and Caicos Islands", "特克斯和凯科斯群岛"),
    "TD": ("Chad", "乍得"),
    "TF": ("French Southern Territories", "法属南部领地"),
    "TG": ("Togo", "多哥"),
    "TH": ("Thailand", "泰国"),
    "TJ": ("Tajikistan", "塔吉克斯坦"),
    "TK": ("Tokelau", "托克劳"),
    "TL": ("Timor-Leste", "东帝汶"),
    "TM": ("Turkmenistan", "土库曼斯坦"),
    "TN": ("Tunisia", "突尼斯"),
    "TO": ("Tonga", "汤加"),
    "TR": ("Türkiye", "土耳其"),
    "TT": ("Trinidad and Tobago", "特立尼达和多巴哥"),
    "TV": ("Tuvalu", "图瓦卢"),
    "TW": ("Taiwan", "台湾"),
    "TZ": ("Tanzania", "坦桑尼亚"),
    "UA": ("Ukraine", "乌克兰"),
    "UG": ("Uganda", "乌干达"),
    "US": ("United States", "美国"),
    "UY": ("Uruguay", "乌拉圭"),
    "UZ": ("Uzbekistan", "乌兹别克斯坦"),
    "VC": ("Saint Vincent and the Grenadines", "圣文森特和格林纳丁斯"),
    "VE": ("Venezuela", "委内瑞拉"),
    "VG": ("British Virgin Islands", "英属维尔京群岛"),
    "VI": ("U.S. Virgin Islands", "美属维尔京群岛"),
    "VN": ("Vietnam", "越南"),
    "VU": ("Vanuatu", "瓦努阿图"),
    "WF": ("Wallis and Futuna", "瓦利斯和富图纳"),
    "WS": ("Samoa", "萨摩亚"),
    "XK": ("Kosovo", "科索沃"),
    "YE": ("Yemen", "也门"),
    "YT": ("Mayotte", "马约特"),
    "ZA": ("South Africa", "南非"),
    "ZM": ("Zambia", "赞比亚"),
    "ZW": ("Zimbabwe", "津巴布韦"),
}


def country_display_names(code: str) -> Tuple[str, str]:
    """
    取国家/地区的英文名与中文名 / Get the English and Chinese names for a code.

    参数 / Parameters:
        code (str): ISO 3166-1 alpha-2 代码，大小写不敏感 /
            ISO 3166-1 alpha-2 code, case-insensitive.

    返回 / Returns:
        tuple[str, str]: (英文名, 中文名)；未收录的代码两者均回退为代码本身，
            空输入返回两个空串 / (English, Chinese); unlisted codes fall back to
            the raw code, and empty input yields two empty strings.

    异常 / Exceptions:
        不抛出异常 / Never raises.
    """
    code = (code or "").strip().upper()
    if not code:
        return "", ""
    return _NAMES.get(code, (code, code))


def known_country_codes() -> Tuple[str, ...]:
    """
    已收录的全部代码 / All codes present in the table.

    返回 / Returns:
        tuple[str, ...]: 按字母排序的代码 / Codes sorted alphabetically.
    """
    return tuple(sorted(_NAMES))
